on:
  push:
    branches:
      - "main"
jobs:
  release:
    if: github.actor == 'KagChi'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      - run: |
          git fetch origin main
          git checkout main
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Compile source
        run: yarn build
      - name: Publish source
        run: |
          npm run release
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'